-- tabela da marca
CREATE TABLE MARCA(
	ID_MARCA NUMBER(7) CONSTRAINT PK_MARCA PRIMARY KEY,
	NOME_MARCA VARCHAR2(120) NOT NULL UNIQUE,
	ATIVO CHAR(1) NOT NULL,
	CONSTRAINT MARCA_ATIVO CHECK(ATIVO IN ('S', 'N'))

);

SELECT * FROM MARCA;
-- sequencia de id_marca
CREATE SEQUENCE SEQ_ID_MARCA
START WITH 100 -- comece com 100
INCREMENT BY 10 -- vai sesr incrementada de 10 em 10
nocycle -- quer dizer que nao vai ser ciclica
NOCACHE
;
-- tabela de modelo
CREATE TABLE MODELO(
	 ID_MARCA NUMBER (7) NOT NULL,
	 ID_MODELO NUMBER(7) NOT NULL,
	 NOME_MODELO VARCHAR2(120) NOT NULL UNIQUE,
	 ATIVO CHAR(1)
		 CONSTRAINT MODELO_ATIVO CHECK( ATIVO IN ('S', 'N')),
	 	 CONSTRAINT FK_TBL_MARCA FOREIGN KEY(ID_MARCA) REFERENCES MARCA(ID_MARCA), -- chave estrageira e qual tabela esta referencicando
		 CONSTRAINT PK_MODELO PRIMARY KEY(ID_MARCA, ID_MODELO)-- chave primaria 

); 

--tabela para versao
CREATE TABLE VERSAO(
    ID_MARCA NUMBER(7) NOT NULL,
    ID_MODELO NUMBER(7) NOT NULL,
    ID_VERSAO NUMBER(7) NOT NULL,
    NOME_VERSAO VARCHAR2(120) NOT NULL,
    ATIVO CHAR(1),
        CONSTRAINT VERSAO_ATIVO CHECK(ATIVO IN('S','s', 'N', 'n')),
     --  CONSTRAINT FK_TBL_MARCA1 FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID_MARCA),
        CONSTRAINT FK_TBL_MODELO FOREIGN KEY (ID_MARCA, ID_MODELO) REFERENCES MODELO(ID_MARCA, ID_MODELO),
        CONSTRAINT PK_VERSAO PRIMARY KEY (ID_MARCA, ID_MODELO, ID_VERSAO)
);

INSERT INTO MARCA(ID_MARCA, NOME_MARCA, ATIVO) VALUES(SEQ_ID_MARCA.NEXTVAL, 'FIAT','N');

INSERT INTO MODELO(ID_MARCA, ID_MODELO, NOME_MODELO, ATIVO) VALUES (100, 1, 'UNO', 'N');

SELECT * FROM MODELO;

/* PROCEDURE INSERIR VEICULO */ 
CREATE OR REPLACE PROCEDURE PROC_INSERIR_VEICULO(
    PAR_MARCA IN MARCA.NOME_MARCA%TYPE,
    PAR_MODELO IN MODELO.NOME_MODELO%TYPE,
    PAR_VERSAO IN VERSAO.NOME_VERSAO%TYPE
    )

IS
VCOUNT_MARCA NUMBER;
VCOUNT_MODELO NUMBER;
VCOUNT_VERSAO_MARCA NUMBER;
VCOUNT_VERSAO_MODELO NUMBER;

VID_MARCA NUMBER;
VID_MODELO NUMBER := 0;
VID_VERSAO NUMBER := 0;

BEGIN
    /* INSERIR MARCA NA TABALA MARCA*/
    SELECT COUNT(*) INTO VCOUNT_MARCA FROM MARCA
        WHERE NOME_MARCA = PAR_MARCA;
        IF VCOUNT_MARCA = 0 THEN
            SELECT SEQ_ID_MARCA. NEXTVAL INTO VID_MARCA FROM DUAL;
            INSERT INTO MARCA(ID_MARCA, NOME_MARCA, ATIVO) VALUES(VID_MARCA, PAR_MARCA, 'N');
            COMMIT;
        ELSE 
            SELECT ID_MARCA INTO VID_MARCA FROM MARCA WHERE NOME_MARCA = PAR_MARCA;
        END IF;
        
/* INSERIR MODELO NA TABELA MODELO*/
        SELECT COUNT (*) INTO VCOUNT_MODELO FROM MODELO 
            WHERE ID_MARCA = VID_MARCA AND NOME_MODELO = PAR_MODELO;
        if VCOUNT_MODELO =0 THEN 
            SELECT MAX(ID_MODELO) INTO VID_MODELO FROM MODELO WHERE 
                ID_MARCA = VID_MARCA;
            VID_MODELO := NVL(VID_MODELO, 0) + 1;
            INSERT INTO MODELO(ID_MARCA, ID_MODELO, NOME_MODELO, ATIVO) VALUES
                (VID_MARCA, VID_MODELO, PAR_MODELO, 'N');
            COMMIT;
        ELSE 
             SELECT ID_MODELO INTO VID_MODELO FROM MODELO WHERE
                NOME_MODELO = PAR_MODELO;
        END IF;        
        
/* INSERIR MODELO NA TABELA MODELO*/
    SELECT COUNT(*) INTO VCOUNT_VERSAO_MARCA FROM VERSAO
    WHERE ID_MARCA = VID_MARCA AND NOME_VERSAO = PAR_VERSAO;
    
    SELECT COUNT(*) INTO VCOUNT_VERSAO_MODELO FROM VERSAO 
    WHERE ID_MODELO = VID_MODELO AND NOME_VERSAO = PAR_VERSAO;
    
    --SE O ID DA MARCA E NOME NAO EXISTIR
    IF VCOUNT_VERSAO_MARCA = 0 THEN
        SELECT MAX(ID_VERSAO) INTO VID_VERSAO FROM VERSAO WHERE ID_MARCA = VID_MARCA;
        VID_VERSAO := NVL(VID_VERSAO, 0) +1;
        INSERT INTO VERSAO(ID_MARCA, ID_MODELO, ID_VERSAO, NOME_VERSAO, ATIVO) VALUES 
            (VID_MARCA, VID_MODELO, VID_VERSAO, PAR_VERSAO, 'N');
        COMMIT;
            ELSE IF  
                VCOUNT_VERSAO_MODELO =0 THEN
                    SELECT(ID_VERSAO) INTO VID_VERSAO FROM VERSAO 
                    WHERE ID_MARCA = VID_MARCA AND NOME_VERSAO = PAR_VERSAO;
                    
                 INSERT INTO VERSAO(ID_MARCA, ID_MODELO, ID_VERSAO, NOME_VERSAO, ATIVO) VALUES 
                    (VID_MARCA, VID_MODELO, VID_VERSAO, PAR_VERSAO, 'N');
                 COMMIT;
                END IF;
        END IF;
                
END PROC_INSERIR_VEICULO;

SELECT * FROM MARCA;

SELECT * FROM MODELO;

SELECT NOME_MARCA, NOME_MODELO, ID_MODELO, NOME_VERSAO, ID_VERSAO FROM VERSAO
    NATURAL JOIN MARCA
    NATURAL JOIN MODELO ORDER BY NOME_MODELO, ID_VERSAO;


BEGIN 
    PROC_INSERIR_VEICULO('GM', 'CORSA', 'SEDAN');
END;